[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/data/config/qBittorrent/data/logs

[AutoRun]
Enabled=true
OnTorrentFinished\Enabled=true
OnTorrentFinished\Program=sh /data/config/qBittorrent/config/notify.sh %N
Program=sh /data/config/qBittorrent/config/notify.sh %N
enabled=true
program=sh /data/config/qBittorrent/config/notify.sh \"%N\"

[BitTorrent]
Session\AddExtensionToIncompleteFiles=true
Session\AddTorrentStopped=false
Session\AddTrackersFromURLEnabled=true
Session\AdditionalTrackersURL=https://cf.trackerslist.com/all.txt
Session\AsyncIOThreadsCount=1
Session\AutoBanUnknownPeer=true
Session\BTProtocol=TCP
Session\ConnectionSpeed=15
Session\DHTEnabled=true
Session\DefaultSavePath=/data/downloads/ok
Session\DiskCacheSize=32
Session\DiskIOReadMode=DisableOSCache
Session\DiskIOWriteMode=DisableOSCache
Session\Encryption=0
Session\ExcludedFileNames=
Session\FilePoolSize=40
Session\FinishedTorrentExportDirectory="/data/downloads/torrent "
Session\IgnoreSlowTorrentsForQueueing=true
Session\LSDEnabled=false
Session\MaxActiveDownloads=3
Session\MaxConnections=100
Session\MaxConnectionsPerTorrent=30
Session\MaxUploads=10
Session\MaxUploadsPerTorrent=2
Session\PeXEnabled=true
Session\Port=6881
Session\Preallocation=false
Session\QueueingSystemEnabled=true
Session\SSL\Port=49490
Session\SendBufferWatermark=2048
Session\ShareLimitAction=Stop
Session\SubcategoriesEnabled=true
Session\TempPath=/data/downloads/temp
Session\TempPathEnabled=true
Session\TorrentExportDirectory="/data/downloads/torrent "
Session\UseCategoryPathsInManualMode=true
Session\UseUPnP=false

[Core]
AutoDeleteAddedTorrentFile=IfAdded

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
PortForwardingEnabled=false
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Bittorrent\DHT=true
Bittorrent\Encryption=0
Bittorrent\LSD=false
Bittorrent\PeX=true
Connection\PortRangeMin=6881
Connection\ResolvePeerCountries=false
Connection\UPnP=false
Downloads\SavePath=/data/downloads
General\Locale=zh_CN
MailNotification\req_auth=true
WebUI\AuthSubnetWhitelist=@Invalid()
WebUI\Locale=zh
WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
WebUI\Port=18080
WebUI\Username=admin

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
